---
- name: Machine setup
  hosts: localhost
  become: false
  connection: localhost
  gather_facts: true

  vars:
    brew_casks:
      - firefox
      - todoist
      - obsidian
      - karabiner-elements
      - bitwarden
      - anki
      - wezterm
    brew_packages:
      - syncthing
      - neovim
      - ripgrep
      - lazygit
      - rm-improved
      - eza
      - go
      - bat
    fish_path: /opt/homebrew/bin/fish

  tasks:
    - name: Get my user
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_facts.user_id}}"

    - name: Install community.general collection
      ansible.builtin.ansible_galaxy:
        type: collection
        name: community.general
        state: present

    - name: Gather package facts
      community.general.homebrew:
        update_homebrew: yes
        list: yes
      register: brew_facts

    - name: Install fish
      ansible.builtin.package:
        name: fish
        state: present

    - name: Add fish to /etc/shells
      ansible.builtin.shell: echo /opt/homebrew/bin/fish | sudo tee -a /etc/shells

    - name: Change shell to fish
      ansible.builtin.command: chsh -s {{ fish_path }}
      become_user: "{{ remote_regular_user }}"

    - name: Intall packages
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"
      when: "item not in brew_facts.packages"

    - name: Install casks
      community.general.homebrew_casks:
        name: "{{ item }}"
        state: latest
      loop: "{{ casks }}"
      when: "item not in brew_facts.packages"

    - name: Install rust
      ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      become_user: "{{ remote_regular_user }}"
