---
- name: Machine setup
  hosts: localhost
  become: false
  connection: localhost
  gather_facts: true

  vars:
    packages:
      - firefox
      - zotero
      - todoist
      - obsidian
      - karabiner-elements
      - syncthing
      - bitwarden
      - anki
      # cli
      - wezterm
      - neovim
      - git
      - ripgrep
      - lazygit
      - rm-improved
      - eza
      - go
    fish_path: /opt/homebrew/bin/fish

  tasks:
    - name: Get my user
      ansible.builtin.set_fact:
        remote_regular_user: "{{ ansible_facts.user_id}}"

    - name: Install fish
      ansible.builtin.package:
        name: fish
        state: present

    - name: Change shell to fish
      ansible.builtin.command: chsh -s {{ fish_path }}
      become_user: "{{ remote_regular_user }}"

    - name: Intall rest of packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

    - name: Install rust
      ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      become_user: "{{ remote_regular_user }}"
